StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64EA224EC076B7AA}" {
   Id "SPC-AmmunitionID_100mm"
   Target_en_us "100×258mm"
   Modified 1693066615
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64EA224FD48E0F9C}" {
   Id "SPC-EditableEntity_Vehicle_BMP3"
   Target_en_us "BMP-3 Infantry Fighting Vehicle"
   Modified 1693065984
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64EA224E1B0D6569}" {
   Id "SPC-Weapon_2A70_Name"
   Target_en_us "2A70"
   Modified 1693066502
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{654959FB5F74E80F}" {
   Id "SPC-Weapon_9M117_Name"
   Target_en_us "9M117 Bastion"
   Modified 1699306797
   Author "mikia"
   LastChanged "mikia"
  }
 }
}